[package]
name = "pytauri-core"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
tauri = { workspace = true }

pyo3 = { workspace = true }
pyo3-utils = { workspace = true }

[features]
__private = []
