// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../app/app.config";
import type { default as appConfig1 } from "../../../node_modules/.pnpm/docus@5.4.0_@babel+parser@7_2de6d94f7438276217e6c7ff31b58012/node_modules/docus/app/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}

}
export {}