// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-site-config@3.2.14_h3@_5b7ee00fd9f1dcef4e92c19980aa4fe8/node_modules/nuxt-site-config/dist/runtime/app/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+content@3.9.0_better-sqlite3@12.5.0_magicast@0.5.1/node_modules/@nuxt/content/dist/runtime/plugins/websocket.dev.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7_e73d30ef682a357faae1c7c41b9934ee/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7_e73d30ef682a357faae1c7c41b9934ee/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhea_2c65eaa94d8813161b3484e23ccd2594/node_modules/nuxt-og-image/dist/runtime/app/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhea_2c65eaa94d8813161b3484e23ccd2594/node_modules/nuxt-og-image/dist/runtime/app/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+robots@5.6.7_h3@1.1_2daea7cac1bd2a39f53cc5ec0606e7bc/node_modules/@nuxtjs/robots/dist/runtime/app/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_62abd4d671a47bb075cd00863fb8aad7/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/@nuxt+icon@2.1.1_magicast@0_0973c9c4c9c4dbbae37b8750b7e8c864/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/nuxt@4.2.2_@parcel+watcher@_bf05da0fe82c47dec278e8643b7e7117/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../../node_modules/.pnpm/docus@5.4.0_@babel+parser@7_2de6d94f7438276217e6c7ff31b58012/node_modules/docus/app/plugins/i18n")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
